const reportsRepository = require("./reports.repository");

class ReportsService {
  async getReportsData() {
    return await reportsRepository.getAggregates();
  }

  async exportCSV(type, user) {
    const userId = user.id; const scope = user.role === "official" ? { department:user.department } : {}; if(!["policies","schemes","user-activity","departments","analytics"].includes(type)) throw new Error("Unsupported report type");
    if(user.role !== "admin" && !["policies","schemes","departments"].includes(type)) throw new Error("Not authorized for this report type");
    let csvData = "";

    if (type === "user-activity") { const rows=await reportsRepository.getActivity(); csvData="Action,User,Role,Details,Timestamp\n"+rows.map(x=>`"${x.action}","${x.userId?.email||""}","${x.userRole}","${(x.details||"").replace(/"/g,'""')}","${x.createdAt.toISOString()}"`).join("\n"); return {csvData,filename:"user_activity_report.csv"};
    }
    if (type === "departments" || type === "analytics") { const data=await reportsRepository.getDepartmentSummary(scope); csvData="Metric,Value\n"+Object.entries(data).map(([k,v])=>`"${k}","${JSON.stringify(v).replace(/"/g,'""')}"`).join("\n"); return {csvData,filename:`${type}_report.csv`};
    }
    if (["user-activity","departments","analytics"].includes(type)) { const generated=await this.exportCSV(type,user); doc.fontSize(16).text(`GovIntel ${type} Report`); doc.moveDown().fontSize(9).text(generated.csvData); doc.end(); return new Promise(resolve=>doc.on("end",()=>resolve({pdfBuffer:Buffer.concat(buffers),filename:`${type}_report.pdf`}))); }
    if (["user-activity","departments","analytics"].includes(type)) { const generated=await this.exportCSV(type,user); generated.csvData.split("\n").forEach(line=>worksheet.addRow(line.split(","))); const excelBuffer=await workbook.xlsx.writeBuffer(); return {excelBuffer,filename:`${type}_report.xlsx`}; }
    if (type === "policies") {
      const policies = await reportsRepository.getPolicies(scope);
      csvData += "Title,Description,Category,Department,State,Status,Deadline,Created Date\n";
      policies.forEach((p) => {
        csvData += `"${p.title.replace(/"/g, '""')}","${p.description.replace(/"/g, '""')}","${p.category}","${p.department}","${p.state}","${p.status}","${p.deadline || "N/A"}","${p.createdAt.toISOString()}"\n`;
      });
      await reportsRepository.createDownloadLog({ userId, type: "csv", target: "policies" });
      return { csvData, filename: "policies_report.csv" };
    } else if (type === "user-activity") { const rows=await reportsRepository.getActivity(); csvData="Action,User,Role,Details,Timestamp\n"+rows.map(x=>`"${x.action}","${x.userId?.email||""}","${x.userRole}","${(x.details||"").replace(/"/g,'""')}","${x.createdAt.toISOString()}"`).join("\n"); return {csvData,filename:"user_activity_report.csv"};
    } else if (type === "departments" || type === "analytics") { const data=await reportsRepository.getDepartmentSummary(scope); csvData=JSON.stringify(data,null,2); return {csvData,filename:`${type}_report.csv`};
    } else {
      const schemes = await reportsRepository.getSchemes(scope);
      csvData += "Title,Description,Category,Department,State,Status,AgeMin,AgeMax,GenderLimit,IncomeMax,Created Date\n";
      schemes.forEach((s) => {
        const rules = s.eligibilityRules || {};
        csvData += `"${s.title.replace(/"/g, '""')}","${s.description.replace(/"/g, '""')}","${s.category}","${s.department}","${s.state}","${s.status}","${rules.ageMin}","${rules.ageMax}","${rules.gender}","${rules.incomeMax || "No Limit"}","${s.createdAt.toISOString()}"\n`;
      });
      await reportsRepository.createDownloadLog({ userId, type: "csv", target: "schemes" });
      return { csvData, filename: "schemes_report.csv" };
    }
  }

  async exportPDF(type, user) {
    const userId=user.id; const scope=user.role === "official"?{department:user.department}:{}; if(!["policies","schemes"].includes(type)) throw new Error("Unsupported report type");
    const PDFDocument = require("pdfkit");
    const doc = new PDFDocument({ margin: 30 });
    const buffers = [];
    doc.on("data", buffers.push.bind(buffers));

    doc.fontSize(20).text(`GovIntel Platform - ${type === "policies" ? "Policies" : "Schemes"} Report`, { align: "center" });
    doc.moveDown();
    doc.fontSize(10).text(`Generated by User ID: ${userId} on ${new Date().toLocaleDateString()}`);
    doc.moveDown();

    if (type === "policies") {
      const policies = await reportsRepository.getPolicies(scope);
      policies.forEach((p, idx) => {
        doc.fontSize(12).fillColor("blue").text(`${idx + 1}. ${p.title}`);
        doc.fontSize(10).fillColor("black").text(`Category: ${p.category} | Department: ${p.department} | State: ${p.state} | Status: ${p.status}`);
        doc.text(`Description: ${p.description}`);
        doc.moveDown();
      });
    } else if (type === "user-activity") { const rows=await reportsRepository.getActivity(); csvData="Action,User,Role,Details,Timestamp\n"+rows.map(x=>`"${x.action}","${x.userId?.email||""}","${x.userRole}","${(x.details||"").replace(/"/g,'""')}","${x.createdAt.toISOString()}"`).join("\n"); return {csvData,filename:"user_activity_report.csv"};
    } else if (type === "departments" || type === "analytics") { const data=await reportsRepository.getDepartmentSummary(scope); csvData=JSON.stringify(data,null,2); return {csvData,filename:`${type}_report.csv`};
    } else {
      const schemes = await reportsRepository.getSchemes(scope);
      schemes.forEach((s, idx) => {
        const rules = s.eligibilityRules || {};
        doc.fontSize(12).fillColor("green").text(`${idx + 1}. ${s.title}`);
        doc.fontSize(10).fillColor("black").text(`Category: ${s.category} | Department: ${s.department} | State: ${s.state} | Status: ${s.status}`);
        doc.text(`Age Min: ${rules.ageMin} | Age Max: ${rules.ageMax} | Gender: ${rules.gender} | Income Max: ${rules.incomeMax || "No Limit"}`);
        doc.text(`Description: ${s.description}`);
        doc.moveDown();
      });
    }

    doc.end();

    return new Promise((resolve) => {
      doc.on("end", async () => {
        const pdfBuffer = Buffer.concat(buffers);
        await reportsRepository.createDownloadLog({ userId, type: "pdf", target: type });
        resolve({ pdfBuffer, filename: `${type}_report.pdf` });
      });
    });
  }

  async exportExcel(type, user) {
    const userId=user.id; const scope=user.role === "official"?{department:user.department}:{}; if(!["policies","schemes"].includes(type)) throw new Error("Unsupported report type");
    const ExcelJS = require("exceljs");
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet(type === "policies" ? "Policies" : "Schemes");

    if (type === "policies") {
      worksheet.columns = [
        { header: "Title", key: "title", width: 30 },
        { header: "Description", key: "description", width: 50 },
        { header: "Category", key: "category", width: 15 },
        { header: "Department", key: "department", width: 15 },
        { header: "State", key: "state", width: 15 },
        { header: "Status", key: "status", width: 15 },
        { header: "Deadline", key: "deadline", width: 20 },
        { header: "Created Date", key: "createdAt", width: 25 },
      ];

      const policies = await reportsRepository.getPolicies(scope);
      policies.forEach((p) => {
        worksheet.addRow({
          title: p.title,
          description: p.description,
          category: p.category,
          department: p.department,
          state: p.state,
          status: p.status,
          deadline: p.deadline ? p.deadline.toISOString() : "N/A",
          createdAt: p.createdAt.toISOString(),
        });
      });
    } else {
      worksheet.columns = [
        { header: "Title", key: "title", width: 30 },
        { header: "Description", key: "description", width: 50 },
        { header: "Category", key: "category", width: 15 },
        { header: "Department", key: "department", width: 15 },
        { header: "State", key: "state", width: 15 },
        { header: "Status", key: "status", width: 15 },
        { header: "Age Min", key: "ageMin", width: 10 },
        { header: "Age Max", key: "ageMax", width: 10 },
        { header: "Gender", key: "gender", width: 10 },
        { header: "Income Max", key: "incomeMax", width: 15 },
        { header: "Created Date", key: "createdAt", width: 25 },
      ];

      const schemes = await reportsRepository.getSchemes(scope);
      schemes.forEach((s) => {
        const rules = s.eligibilityRules || {};
        worksheet.addRow({
          title: s.title,
          description: s.description,
          category: s.category,
          department: s.department,
          state: s.state,
          status: s.status,
          ageMin: rules.ageMin,
          ageMax: rules.ageMax,
          gender: rules.gender,
          incomeMax: rules.incomeMax || "No Limit",
          createdAt: s.createdAt.toISOString(),
        });
      });
    }

    worksheet.getRow(1).font = { bold: true };

    const excelBuffer = await workbook.xlsx.writeBuffer();
    await reportsRepository.createDownloadLog({ userId, type: "excel", target: type });
    return { excelBuffer, filename: `${type}_report.xlsx` };
  }
}

module.exports = new ReportsService();
