version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: govintel_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: govintel_api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/policy_platform
      - JWT_SECRET=super_secret_jwt_key_123!
    depends_on:
      - mongo

volumes:
  mongo_data:
