const express = require("express");
const router = express.Router();
const { getNotifications, markAsRead, markAllRead, deleteNotification } = require("./notifications.controller");
const { protect } = require("../auth/auth.middleware");
router.get("/", protect, getNotifications);
router.patch("/read-all", protect, markAllRead);
router.put("/read-all", protect, markAllRead);
router.patch("/:id/read", protect, markAsRead);
router.put("/:id/read", protect, markAsRead);
router.delete("/:id", protect, deleteNotification);
module.exports = router;
