import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import policyService from "../../services/policy.service";
import { ArrowLeftRight, Trash2 } from "lucide-react";
import { toast, Toaster } from "react-hot-toast";

const value=(item,key)=>{if(key.startsWith("eligibility.")){const k=key.split(".")[1],r=item.eligibilityRules||{};const v=r[k];if(k==="age")return `${r.ageMin??0}–${r.ageMax??120} years`;if(k==="incomeMax")return v==null?"No limit":`₹${v}`;if(k==="disabilityRequired")return v?"Required":"Not required";return v||"Not specified";} if(key==="document")return item.document?.name||"Not specified"; if(key.endsWith("Date")||key==="deadline")return item[key]?new Date(item[key]).toLocaleDateString():"Not specified";return item[key]||"Not specified";};
const policyRows=[["Department","department"],["Category","category"],["Sector","sector"],["Ministry","ministry"],["Official Reference","officialReference"],["State / Jurisdiction","state"],["Publication Date","publicationDate"],["Effective Date","effectiveDate"],["Deadline","deadline"],["Benefits","benefits"],["Application Process","applicationProcess"],["Source URL","sourceUrl"],["Status","status"],["Version","version"],["Official Document","document"]];
const schemeRows=[...policyRows,["Age","eligibility.age"],["Gender","eligibility.gender"],["Income Limit","eligibility.incomeMax"],["Occupation","eligibility.occupation"],["Education","eligibility.education"],["Eligibility State","eligibility.state"],["Social Category","eligibility.category"],["Disability","eligibility.disabilityRequired"]];
export default function Compare(){const[list,setList]=useState([]);useEffect(()=>{const saved=JSON.parse(localStorage.getItem("compareList")||"[]");setList(saved);Promise.all(saved.map(i=>i.type==="policy"?policyService.getPolicyById(i._id):policyService.getSchemeById(i._id))).then(r=>setList(r.map((x,i)=>({... (x.policy||x.scheme),type:saved[i].type}))).catch(()=>{});},[]);const remove=id=>{const next=list.filter(x=>x._id!==id);setList(next);localStorage.setItem("compareList",JSON.stringify(next));};const clear=()=>{setList([]);localStorage.removeItem("compareList")};const rows=(list[0]?.type==="scheme"?schemeRows:policyRows);const differs=k=>new Set(list.map(i=>value(i,k))).size>1;return <div className="space-y-6"><Toaster/><div className="flex flex-wrap justify-between gap-3"><div><h1 className="flex gap-2 text-2xl font-bold text-slate-800"><ArrowLeftRight className="text-blue-600"/>Comparison</h1><p className="text-sm text-slate-500">{list.length} of 3 items selected</p></div><div className="flex gap-2"><Link to={list[0]?.type==="scheme"?"/schemes":"/policies"} className="rounded-xl border px-3 py-2 text-xs font-bold">Add another</Link><button onClick={clear} className="rounded-xl border border-red-200 px-3 py-2 text-xs font-bold text-red-600">Clear</button></div></div>{!list.length?<div className="rounded-2xl bg-white p-12 text-center shadow-sm">Select up to three policies or schemes to compare.</div>:<><div className="hidden overflow-x-auto rounded-2xl bg-white shadow-sm md:block"><table className="w-full text-left text-sm"><thead><tr><th className="p-4">Criteria</th>{list.map(i=><th key={i._id} className="border-l p-4"><button onClick={()=>remove(i._id)} className="float-right text-red-500"><Trash2 className="h-4"/></button>{i.title}</th>)}</tr></thead><tbody>{rows.map(([label,key])=><tr key={key} className={differs(key)?"bg-blue-50/50":""}><td className="p-4 text-xs font-bold text-slate-500">{label}</td>{list.map(i=><td key={i._id} className="border-l p-4 text-xs">{value(i,key)}</td>)}</tr>)}</tbody></table></div><div className="space-y-4 md:hidden">{rows.map(([label,key])=><section key={key} className={"rounded-xl bg-white p-4 shadow-sm "+(differs(key)?"ring-1 ring-blue-200":"")}><b className="text-xs text-slate-500">{label}</b>{list.map(i=><p key={i._id} className="mt-2 text-sm"><span className="font-semibold">{i.title}:</span> {value(i,key)}</p>)}</section>)}</div></>}</div>}
